"""add ai conversations messages and settings

Revision ID: dc537f719f1f
Revises: a9e053bc3872
Create Date: 2026-09-17 16:08:56.016328

第六版(AI 接入)的三张表。两处**看着像随手写、其实是故意的**:

  · `ai_conversations.created_by` 是 **NOT NULL + CASCADE**,与 blog_posts /
    comments / activity_events 的 SET NULL 相反。那些是共享内容或审计记录
    (作者走了东西还得留着给人看);会话是**私有**的,作者一走这行就没有任何人
    有权限打开。先例是 sessions.user_id。见 models.AiConversation 的类注释。

  · `ai_messages.reasoning_content` 是**可空**的,而且 NULL 与 '' 必须是两回事:
    DeepSeek 在带 tools 时要求回传历史轮次的 reasoning_content,「没有这个字段」
    与「有但是空串」在协议上是两种东西。见 models.AiMessage 的长注释。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc537f719f1f'
down_revision: Union[str, Sequence[str], None] = 'a9e053bc3872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_created_by'), 'ai_conversations', ['created_by'], unique=False)
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('monthly_token_budget', sa.Integer(), nullable=True),
    sa.Column('daily_questions_per_user', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('max_tokens_per_call', sa.Integer(), server_default=sa.text('4096'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('reasoning_content', sa.Text(), nullable=True),
    sa.Column('tool_trace', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'running'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_created_at'), 'ai_messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_messages_created_at'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_table('ai_settings')
    op.drop_index(op.f('ix_ai_conversations_created_by'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
